### ISSUE TITLE
Error when data length is < 3

### ISSUE THREAD

**Issue by bhrousseau** [einar-saukas/ZX0-Java#2]
It's not possible to encode a file of 1 or 2 byte length.

```
ZX0 v2.1: Optimal data compressor by Einar Saukas
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at compiledSprite/zx0.Optimizer.optimize(Optimizer.java:63)
	at compiledSprite/zx0.Main.zx0(Main.java:47)
	at compiledSprite/zx0.Main.main(Main.java:171)
```

**Comment by einar-saukas** [comment]
This bug was present in all implementations, including the original C version. Thanks a lot for reporting it! It's fixed now.
